### ISSUE TITLE
Ability to remove "Registration is disabled. Ban Hammer will not work."

### ISSUE THREAD

**Issue by gunnsth** [Ipstenu/ban-hammer#3] opened 2017-05-08 09:04 UTC
There is more than one way to register users in Wordpress.  It can also be done programmatically in themes and plugins. In those cases, the option to register normally is often disabled.

Thus it would be convenient to have the means to disable this.

**Comment by Ipstenu** [comment] 2017-05-08 23:16
The plugin depends entirely on using the WordPress registration feature. If you disable it, the plugin won't work as expected and I don't care to support it. Plugins and themes can enhance registration without requiring you to disable it, and programmatically adding users outside of the registration system implies you already have a way to stop random people from registration. That's why you closed it and locked it down :)

**Closed as completed by Ipstenu** 2017-05-08 23:16 UTC
Labels: wontfix

**Comment by amityweb** [comment] 2021-02-19 17:15
Need a way to hide this message. Can you add a close tab like all other notices?

For info, its working fine. We are using WP Foro forum and Gravity Forms user registration, both working fine with registration and ban hammer, so we just need the ability to close this message.

**Comment by Ipstenu** [comment] 2021-02-19 20:41
I'd rather not, since then I just get people who legit disabled registration being pissed off that the plugin doesn't work (which ... I mean, hi? :D ) BUT! Can you link to those plugins? I could possibly add in a check to see if they're active and working and then use that as a hide clause.

**Comment by amityweb** [comment] 2021-02-19 22:54
What I mean is, show the message as you do, but add a dismiss button like other plugins. So everyone will see it and know your concern but can get rid of it when they know it works. Leaving warnings in Wordpress is one of the most annoying things developers can do with their plugins. Or just show it on your plugin page. 

This is WPForo https://wpforo.com/ with its own registration process and works with your plugin with registration disabled. 

Gravity forms user registration which also registers when user registration is disabled in Wordpress https://www.gravityforms.com/add-ons/user-registration/. I actually haven’t tested your plugin with this.

**Comment by Ipstenu** [comment] 2021-02-20 00:10
I understand that, but the problem is that you're the minority here. 

The alert is self-dismissable when the requirements for it's use are met. That is both within the letter and spirit of the WordPress guidelines :) You're the exception in that you have a way 'around' the expected requirement.

One could rightly argue the problem is WPForo and GF are doing it wrong, because instead of hooking into and enhancing the WordPress registration feature, they replaced it.

I skimmed https://wpforo.com/documentation/ but I don't see any information about registration hooks which ... sucks.

I'll do what I did for a couple other plugins and add it in here - https://github.com/Ipstenu/ban-hammer/blob/trunk/ban-hammer.php#L158 - so it checks "Is this plugin active? Ignore." Doesn't really address the crux of the issue, mind, which is that Ban Hammer cannot properly check if you're meeting the requirements (i.e. you actually allow registration)

**Comment by Ipstenu** [comment] 2021-03-07 17:05
Okay changing this, I'll remove it going forward, after WP 5.7 is out.

**Comment by amityweb** [comment] 2021-03-07 19:46
I tested it with gravity forms user registration and it didn’t work. So I added some code to the functions file based on your plugin code, to call ban hammer when user registration through gravity turns happens and it works great. Have you got documentation on how to add your custom code? That would help developers a lot. Let me know if you want the gravity forms code.

**Comment by Ipstenu** [comment] 2021-03-07 21:16
I have https://github.com/Ipstenu/ban-hammer/wiki#woocommerce

I'd love the GF code :) I'll add it to that wiki.

**Comment by amityweb** [comment] 2021-03-08 09:22
This is what I added for Gravity Forms user registration. You may want to improve it some, but I think it would be great you had a collection of these sorts of things to accommodate for additional plugins. Its great that Banhammer can be called from the functions.php because I almost modified your plugin until I thought to try it! I had some trouble matching fields and accessing $form['errors']. $_POST['input_2'] may not be the best way to access the forms email field perhaps but as with all my code is quick and dirty usually as I am on the clock!

```
function gravity_form_user_registration_validation( $form )
{
	$form['errors'] = new WP_Error();
	$BanHammer = new BanHammer();
	if ( $BanHammer->banhammer_drop( $form['user_name'], $_POST['input_2'], $form['errors'] ) )
	{
		$form = gf_user_registration()->add_validation_error( 2, $form, 'Your email has been banned from registration. Please use your business email address and not a free or non-business email address.' );
	}
    return $form;
}
add_filter( 'gform_user_registration_validation', 'gravity_form_user_registration_validation', 10, 3 );
```

**Comment by Ipstenu** [comment] 2021-03-09 00:55
Boom, added - https://github.com/Ipstenu/ban-hammer/wiki#gravity-forms
